@startuml
class Student {
+id: Long
+name: String
+getName(): String
}
class Professor {
+id: Long
+name: String
+subjects: Subject[]
+getName(): String
}
class Subject {
+id: Long
+name: String
+getName(): String
+professors: Professor[]
+students: Student[]
}
class Course {
+id: Long
+name: String
+schedule: DateTime
+professor: Professor
+student: Student
+getName(): String
}
class Grade {
+id: Long
+grade: Double
+getGrade(): Double
}
class Enrollment {
+id: Long
+subjects: Subject[]
}

Student"1" ---> "1"Enrollment
Subject"1" --l-> "1..*"Course
Subject"1" ---> "1"Grade
Professor"1" ---> "*"Subject
Student"1" --l-> "1..*"Subject
Enrollment"1" --> "1..*"Subject
@enduml